sudo: yes
language: cpp

## Install ninja
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - ninja-build
            - gcc-8
            - g++-8

## Compilations and tests
matrix:
    include:
        ## Linux-x86
        ## --------------------------------------------------------------------------------------------
        ## SSE2:
        - os: linux
          compiler: gcc
          env:
            - SIMD=SSE2
        ## SSE42:
        - os: linux
          compiler: gcc
          env:
            - SIMD=SSE42
        ## AVX:
        - os: linux
          compiler: gcc
          env:
            - SIMD=AVX
        ## AVX2:
        - os: linux
          compiler: gcc
          env:
            - SIMD=AVX2
        ## AVX2+FMA:
        - os: linux
          compiler: gcc
          env:
            - SIMD=AVX2
            - SIMD_OPTIONALS=FMA

## List all available compilers
before_install:
    - sudo apt-cache search clang

## Prepare build
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=$CXX -DSIMD=$SIMD -DSIMD_OPTIONALS=$SIMD_OPTIONALS -GNinja

## Build
script:
    - ninja
