language: cpp

## Install deps
addons:
    homebrew:
        packages:
            - ninja
            - clang-format
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
            - ninja-build
            - gcc-8
            - g++-8
            - clang-6.0
            - libmpfr-dev

## Compilations and tests
matrix:
    include:
        ### Linux-gcc-x86
        ### --------------------------------------------------------------------------------------------
        ### SSE2:
        #- os: linux
        #  env:
        #    - TOOLSET=g++-8
        #    - SIMD=SSE2
        ### SSE42:
        #- os: linux
        #  env:
        #    - TOOLSET=g++-8
        #    - SIMD=SSE42
        ### AVX:
        #- os: linux
        #  env:
        #    - TOOLSET=g++-8
        #    - SIMD=AVX
        ### AVX2:
        #- os: linux
        #  env:
        #    - TOOLSET=g++-8
        #    - SIMD=AVX2
        ### AVX2+FMA:
        #- os: linux
        #  env:
        #    - TOOLSET=g++-8
        #    - SIMD=AVX2
        #    - SIMD_OPTIONALS=FMA
        ### Linux-clang-x86
        ### --------------------------------------------------------------------------------------------
        ### SSE2:
        #- os: linux
        #  env:
        #    - TOOLSET=clang++-6.0
        #    - SIMD=SSE2
        ### SSE42:
        #- os: linux
        #  env:
        #    - TOOLSET=clang++-6.0
        #    - SIMD=SSE42
        ### AVX:
        #- os: linux
        #  env:
        #    - TOOLSET=clang++-6.0
        #    - SIMD=AVX
        ### AVX2:
        #- os: linux
        #  env:
        #    - TOOLSET=clang++-6.0
        #    - SIMD=AVX2
        ### AVX2+FMA:
        #- os: linux
        #  env:
        #    - TOOLSET=clang++-6.0
        #    - SIMD=AVX2
        #    - SIMD_OPTIONALS=FMA
        ### OSX-clang-x86
        ### --------------------------------------------------------------------------------------------
        ### SSE2:
        #- os: osx
        #  env:
        #    - TOOLSET=clang++
        #    - SIMD=SSE2
        ### SSE42:
        #- os: osx
        #  env:
        #    - TOOLSET=clang++
        #    - SIMD=SSE42
        ### AVX:
        #- os: osx
        #  env:
        #    - TOOLSET=clang++
        #    - SIMD=AVX
        ### AVX2:
        #- os: osx
        #  env:
        #    - TOOLSET=clang++
        #    - SIMD=AVX2
        ### AVX2+FMA:
        #- os: osx
        #  env:
        #    - TOOLSET=clang++
        #    - SIMD=AVX2
        #    - SIMD_OPTIONALS=FMA
        ## Windows-MSVC-x86
        ## --------------------------------------------------------------------------------------------
        ## SSE2:
        - os: windows
          env:
            - TOOLSET=cl
            - SIMD=SSE2
        ## SSE42:
        - os: windows
          env:
            - TOOLSET=cl
            - SIMD=SSE42
        ## AVX:
        - os: windows
          env:
            - TOOLSET=cl
            - SIMD=AVX
        ## AVX2:
        - os: windows
          env:
            - TOOLSET=cl
            - SIMD=AVX2
        ## AVX2+FMA:
        - os: windows
          env:
            - TOOLSET=cl
            - SIMD=AVX2
            - SIMD_OPTIONALS=FMA

## It seems that travis ignore addons "chocolatey" so do it manually
install:
    - if [[ $TRAVIS_OS_NAME == 'windows' ]]; then (
        choco install ninja
        choco install llvm
      ) fi

## Prepare build
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET -DSIMD=$SIMD -DSIMD_OPTIONALS=$SIMD_OPTIONALS -GNinja

## Build
script:
    - ninja
    - ninja gen.tests
    - ninja tests
    - ctest .
