language: cpp

## Install ninja
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
            - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-6.0 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
        packages:
            - ninja-build
            - gcc-8
            - g++-8
            - clang-6.0

## Compilations and tests
matrix:
    include:
        ## Linux-gcc-x86
        ## --------------------------------------------------------------------------------------------
        ## SSE2:
        - os: linux
          env:
            - TOOLSET=g++-8
            - SIMD=SSE2
        ## SSE42:
        - os: linux
          env:
            - TOOLSET=g++-8
            - SIMD=SSE42
        ## AVX:
        - os: linux
          env:
            - TOOLSET=g++-8
            - SIMD=AVX
        ## AVX2:
        - os: linux
          env:
            - TOOLSET=g++-8
            - SIMD=AVX2
        ## AVX2+FMA:
        - os: linux
          env:
            - TOOLSET=g++-8
            - SIMD=AVX2
            - SIMD_OPTIONALS=FMA

## Prepare build
before_script:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=$TOOLSET -DSIMD=$SIMD -DSIMD_OPTIONALS=$SIMD_OPTIONALS -GNinja

## Build
script:
    - ninja
